version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - tickets-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_PASSWORD: insecure # change this to a secure password
      MYSQL_ROOT_PASSWORD: insecure # change this to a (different) secure password
      MYSQL_USER: tickets

  bot:
    image: eartharoid/discord-tickets:4.0
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - 8169:8169
    volumes:
      - tickets-bot:/home/container/user
    tty: true
    stdin_open: true
    # Please refer to the documentation:
    # https://discordtickets.app/self-hosting/configuration/#environment-variables
    environment:
      DB_CONNECTION_URL: mysql://tickets:insecure@mysql/tickets # change `insecure` to the MYSQL_PASSWORD you set above
      DISCORD_SECRET: # required
      DISCORD_TOKEN: # required
      ENCRYPTION_KEY: # required
      DB_PROVIDER: mysql
      HTTP_EXTERNAL: http://127.0.0.1:8169 # change this to your server's external IP (or domain)
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: "false" # set to true if you're using a reverse proxy
      OVERRIDE_ARCHIVE: null
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: 319467558166069248 # optionally add `,youruseridhere`

networks:
  discord-tickets:

volumes:
  tickets-mysql:
  tickets-bot:
